### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by Aeylita44** [Micalobia/Full-Slabs#40]
It seems like there's a couple mods that are missing visible assets for the mod. I am using the Benchmark mod pack for fabric game version 1.17.1 and mod version 3.1.3. I tested out placing a slab for each mod that was in the pack and the only two that gave issues were:
-Better Nether (Horizontal)
-Mo Glass (Horizontal & Vertical)

I will attach screenshots of what I am seeing and my log file.
Thanks!!

[latest.log](https://github.com/Micalobia/Full-Slabs/files/7271652/latest.log)

![Willow1](https://user-images.githubusercontent.com/91788950/135721361-2de80902-ef6f-4761-85d6-8e1e285bce5a.png)
![Willow2](https://user-images.githubusercontent.com/91788950/135721363-aabde9fb-fc0c-4d84-9f40-dde105a4c4b9.png)
![Willow3](https://user-images.githubusercontent.com/91788950/135721368-81d0c7e4-6f51-4a45-8ead-da2b924c68be.png)

![MoGlass](https://user-images.githubusercontent.com/91788950/135721372-0a0dc0dc-d907-41ad-862c-00cd9052fdc3.png)

**Comment by Micalobia** [comment]
Thank you for reporting, I'll look into this soon!

**Comment by DaveyL2013** [comment]
Mo Glass seems to render the textures just fine when it's a horizontal slab (but it becomes solid so you can't see through it), so I'd say the issue probably has to do with full slabs not having support for transparent slabs. As for vertical glass slabs, I'm fairly certain that something there is incompatible with the way Mo Glass is programmed to have the transparency work between multiple types of glass (which you can see when you place vertical glass panes on their own, they self cut-off half way up the block) , and you would probably need to make custom code to fix that for the vertical slabs since Mo Glass doesn't have anything it it to handle vertical glass slabs. Although I have no idea if any of this is correct and is just my best guess, I just am putting ideas here because I like both of these mods and would very much like them to be compatible with each other one day.

**Comment by Micalobia** [comment]
Yeah, the mixed slabs didn't handle transparency before. The weird cutting-in-half thing is actually a thing that can be changed in a config, although I need to change where I put the config. Basically, the glass slabs need to be tilted, kinda like what smooth stone slabs do, that way it doesn't look weird.

**Comment by Micalobia** [comment]
I've made a patch for it, will release something most likely this weekend

**Comment by Aeylita44** [comment]
I have a home built with willow and willow slabs so that's what my caught my eye. I only discovered the mo glass "issue" when testing the rest to be thorough. So excited to redo the house with the update though!

**Comment by Micalobia** [comment]
So there's a config file in your config folder, any slabs that need to be tilted needs to go in there essentially. This is the one that'd needed for Mo Glass
`full_slabs.json`:
```json
{
  "tiltableSlabs": [
    "minecraft:smooth_stone_slab",
    "mo_glass:glass_slab",
    "mo_glass:white_stained_glass_slab",
    "mo_glass:orange_stained_glass_slab",
    "mo_glass:magenta_stained_glass_slab",
    "mo_glass:light_blue_stained_glass_slab",
    "mo_glass:yellow_stained_glass_slab",
    "mo_glass:lime_stained_glass_slab",
    "mo_glass:pink_stained_glass_slab",
    "mo_glass:gray_stained_glass_slab",
    "mo_glass:light_gray_stained_glass_slab",
    "mo_glass:cyan_stained_glass_slab",
    "mo_glass:purple_stained_glass_slab",
    "mo_glass:blue_stained_glass_slab",
    "mo_glass:brown_stained_glass_slab",
    "mo_glass:green_stained_glass_slab",
    "mo_glass:red_stained_glass_slab",
    "mo_glass:black_stained_glass_slab"
  ]
}
```
