### ISSUE TITLE
Config/hotkey to enable/disable vertical slabs

### ISSUE THREAD

**Issue by Kasprenius** [Micalobia/Full-Slabs#49]
Please oh please! With the newest update I want it even more!

**Comment by shaneknysh** [comment]
Not sure if this is could be done with the same hotkey - lock slabs into an orientation. Unlike @kasprenius we LOVE vertical slabs and would like to be able to lock the orientation of slabs so to allow fast placement of rows of vertical slabs for building. 

I can create a new issue if this different enough to be addressed separately.

**Comment by xanthian** [comment]
indeed, a hot key to cycle Vertical//Horizontal//Standard placement would be great, this would be helpful when trying to build long slab paths etc..
Standard would then just use the widget to place where needed for smaller build projects.

**Comment by Skeithh** [comment]
would be great to have, while some folks in my server can manage with the current system, it has become a big frustration for others...

**Comment by Micalobia** [comment]
Should be in the latest version now (3.2.2), it toggles between horizontal/universal mode. It doesn't have a default keybind
Might make it cycle, it'd been a while since I looked at this issue and it evolved since I last looked
Will create another issue to make it cycle, code is going through some changes to make dev easy atm
