### ISSUE TITLE
All horizontal slabs went vertical

### ISSUE THREAD

**Issue by AstoriaWinters** [Micalobia/Full-Slabs#69]
So, I installed this mod in an already established world. Thinking nothing of it. Unfortunately, it has made *every single* slab that was already placed, vertical. My Staff and I have just spent the better part of 3hrs fixing things, but could this be fixed in future? I feel bad for anyone else who has to go thru that.

**Comment by Micalobia** [comment]
That shouldn't be possible, it's *supposed* to default to vanilla slab positions. Is that in the 1.18 version, and what other mods do you have installed?
It might fix itself if the mod is uninstalled, but vertical slabs would also go horizontal in that case for obvious reasons.

**Comment by AstoriaWinters** [comment]
It is the 1.18 version yes, and my server has about 70 mods required by the player and another 40 or so that are server only (its an origins server).  I don't *think* there's anything that would affect the slabs like this? But I am going to go into SP today and test it out as well. Try to see what mod the issue lies in. On that note tho- Additional Bars mod, the horizontal bars crash when seen vertical which was interesting lol

Also ran into a problem where apparently the slabs will reset back into vertical after being fixed to be horizontal. I attached 2 pics one of my players sent me of the issue as well.

![2022-01-01_09 46 29](https://user-images.githubusercontent.com/86344310/147848597-72426e57-4e6d-4f0c-aed5-a53422e27a47.png)
![2022-01-01_09 46 49](https://user-images.githubusercontent.com/86344310/147848599-7b64107c-a696-46f9-9bb4-2cb2a29ee9c6.png)
l

**Comment by AstoriaWinters** [comment]
So, just tested it. all I have is- Full Slabb 3.3.1, Fabric API 0.45.0 and Cloth Config 6.1.48. I have the latest version of Cloth Cofig and Fabric API, so I am unsure.
![image](https://user-images.githubusercontent.com/86344310/147848805-4d38668a-d093-4ef6-9182-c1a840d162f1.png)

**Comment by AstoriaWinters** [comment]
Here is the log file that goes with that screenshot btw. I forgot to add ti in there.

[latest.log](https://github.com/Micalobia/Full-Slabs/files/7797579/latest.log)

**Comment by Joulanh** [comment]
I just wanted to report this so i did some testing myself. The only thing i'd add is that after removing the mod, as far as i know slabs, stairs, stripped logs and trapdoors are all set into the same rotation or blockstate. 

And there is another critical bug. If you remove the mod, leaves start to decay in the chunks that were loaded with the mod installed. I had this issue after i removed the mod on my server because it set all slabs to vertical, and since i have a mod installed that lets leaves decay faster suddendly every single leave around me was gone. If you wanna test this without extra mods, raising the gamerule randomtickspeed is a good way to go.

Here are some screenshots in order: Full slabs never installed -> with fullslabs installed afterwarts -> after removing fullslabs again

Before installing fullslabs:

![2022-01-01_14 35 30](https://user-images.githubusercontent.com/80494384/147852036-5ec005ad-743f-400f-993f-626996cd12b0.png)

![2022-01-01_14 44 24](https://user-images.githubusercontent.com/80494384/147852062-b7414ff3-14dc-4be3-8ea4-435b3152f7f6.png)

With fullslabs installed:
(I added a leavebush because the decay also includes leaves with the persistent tag)
-> only the slabs turned vertical

![2022-01-01_14 42 06](https://user-images.githubusercontent.com/80494384/147852073-4301feba-d612-46a4-9530-a41cb28b41cc.png)

![2022-01-01_14 44 24](https://user-images.githubusercontent.com/80494384/147852107-67d589fe-7bf0-4950-ae79-0e3122ff55ba.png)

After removing fullslabs:
-> stripped logs, stairs, slabs, and trapdoors rotation was changed compared to before installing fullslabs
-> some leaves decayed on trees, leaves on the ground are gone

![2022-01-01_14 43 57](https://user-images.githubusercontent.com/80494384/147852116-13f1d787-4359-4a8f-b23d-06937752656a.png)

![2022-01-01_14 46 11](https://user-images.githubusercontent.com/80494384/147852119-f9c436cc-5039-4f62-a334-adbfce6b8c05.png)

After repeating installing and removing the mod for a second time:
-> all leaves are gone now

![2022-01-01_14 46 16](https://user-images.githubusercontent.com/80494384/147852157-10accaa4-7752-40ef-81a9-160462400230.png)

**Comment by Micalobia** [comment]
This is super weird, might be a bug with the Statement API, will 100% have to look more into this, thank you for reporting, y'all got very in-depth which is extremely helpful

**Comment by dandin87** [comment]
This is also happening on All of Fabric 5. already placed slabs turn vertical.

**Comment by Micalobia** [comment]
This is waiting on https://github.com/Virtuoel/Statement/issues/13, which is then waiting on [Virtuoel/Statement/milestone/1](https://github.com/Virtuoel/Statement/milestone/1).

Don't pester Virtuoel about it, hopefully the fix is soon but patience is important.

**Comment by Micalobia** [comment]
This is resolved now in Full Slabs 3.3.3, thank y'all for your patience!
